name: multiregex
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - pyahocorasick
  - pip
  - pre-commit
  - pytest>=6  # Adds --import-mode option
  - pytest-cov

  # Docs
  # - make
  # - numpydoc
  # - setuptools_scm
  # - sphinx
  # - sphinxcontrib-apidoc
  # - sphinx_rtd_theme

  # Build
  # -flit
